fix

diff --git a/build b/build
--- a/build
+++ b/build
@@ -9,10 +9,10 @@ if [ -d $strBuildDirectory ]; then
     cd $strBuildDirectory
 fi
 
-if [ "$EUID" -ne 0 ]; then 
-    echo "[ERROR] You have to run this script as root user!"
-    exit 1
-fi
+# if [ "$EUID" -ne 0 ]; then 
+#     echo "[ERROR] You have to run this script as root user!"
+#     exit 1
+# fi
 
 function ProgressCheck() {
     if [ $? -eq 0 ]; then
